"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { AlertTriangle, BedDouble, Building2, CheckCircle2, ChevronLeft, ChevronRight, CloudDownload, Compass, Fuel, HeartPulse, Home, Hotel, LayoutDashboard, LocateFixed, MapPin, Menu, Navigation, PhoneCall, PlugZap, Plus, Search, ShieldCheck, Users, WifiOff, X } from "lucide-react";
import { nearbyPlaces, treks, warnings as warningData } from "@/data/mockData";
import abcPlacesJson from "@/data/abcPlaces.json";
import abcRouteJson from "@/data/abcRoute.json";
import { assessRoute } from "@/lib/routeSafety";
import { cacheOfflineAssets, getRoutePackage, getStoredWarnings, saveRoutePackage, saveWarning } from "@/lib/offlineStore";
import type { ConfirmationKind, MapPlace, NearbyPlace, OfflineRoutePackage, Trek, Warning, WarningStatus } from "@/lib/models";
import { mockTrekService } from "@/services/trekService";
import { warningApi } from "@/services/warningApi";
import { RouteMap } from "@/components/RouteMap";
import { TrailCard } from "@/components/TrailCard";
import { WarningCard } from "@/components/WarningCard";
import { WarningComposer } from "@/components/WarningComposer";
import { CoordinatorDashboard } from "@/components/CoordinatorDashboard";

type Screen = "home" | "explore" | "nearby" | "community" | "coordinator" | "details";
const mapPlaces = abcPlacesJson as MapPlace[];
const navItems: { id: Exclude<Screen, "details">; label: string; icon: typeof Home }[] = [
  { id: "home", label: "Home", icon: Home }, { id: "explore", label: "Explore", icon: Compass }, { id: "nearby", label: "Nearby", icon: MapPin }, { id: "community", label: "Community", icon: Users }, { id: "coordinator", label: "Coordinator", icon: LayoutDashboard },
];
const contacts = [
  { label: "Tourist Police", number: "1144", note: "Nepal Tourism Board listed toll-free hotline" },
  { label: "Nepal Police", number: "100", note: "Police assistance" },
  { label: "Tourist Police Pokhara", number: "061-462761", note: "Gandaki Province contact" },
];
const checkpoints = ["Birethanti Tourist Police", "Ghandruk Tourist Police", "Chhomrong route settlement"];
const activeStatuses: WarningStatus[] = ["unconfirmed", "community_confirmed", "guide_verified", "disputed"];

function mergeWarnings(...sets: Warning[][]) { const byId = new Map(warningData.map((warning) => [warning.id, warning])); sets.flat().forEach((warning) => byId.set(warning.id, warning)); return Array.from(byId.values()); }
function mergeStoredAndRemote(stored: Warning[], remote: Warning[]) {
  const byId = new Map(warningData.map((warning) => [warning.id, warning]));
  remote.forEach((warning) => byId.set(warning.id, warning));
  stored.forEach((warning) => { if (warning.syncStatus === "pending" || !byId.has(warning.id)) byId.set(warning.id, warning); });
  return Array.from(byId.values());
}
function AppLogo() { return <div className="brand" aria-label="My Sherpa"><span className="brand-mark"><svg viewBox="0 0 40 40" aria-hidden="true"><path d="M7 28 17.5 11l5.3 8.2 3.3-4.5L34 28H7Z"/><path d="m13 28 6.2-9.7L22 22l2.3-2.8L30 28H13Z"/></svg></span><span><strong>My Sherpa</strong><small>Trek safety</small></span></div>; }
function SafetyBadge({ trek }: { trek: Trek }) { return <span className={`safety-badge safety-badge--${trek.safety.toLowerCase().replace(" ", "-")}`}><ShieldCheck size={16} />{trek.safety}</span>; }

export default function MySherpaApp() {
  const [screen, setScreen] = useState<Screen>("home");
  const [selectedTrek, setSelectedTrek] = useState<Trek>(treks[0]);
  const [query, setQuery] = useState(""); const [results, setResults] = useState<Trek[]>(treks); const [loading, setLoading] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false); const [composerOpen, setComposerOpen] = useState(false); const [assistanceOpen, setAssistanceOpen] = useState(false);
  const [selectedWarning, setSelectedWarning] = useState<Warning | null>(null); const [expandedWarnings, setExpandedWarnings] = useState(false); const [toast, setToast] = useState(""); const [nearbyFilter, setNearbyFilter] = useState("All");
  const [postedWarnings, setPostedWarnings] = useState<Warning[]>(warningData); const [offlinePackage, setOfflinePackage] = useState<OfflineRoutePackage>();
  const [online, setOnline] = useState(true); const [syncing, setSyncing] = useState(false); const [storageLoading, setStorageLoading] = useState(true);
  const pendingCount = postedWarnings.filter((warning) => warning.syncStatus === "pending").length;
  const routeWarnings = useMemo(() => postedWarnings.filter((warning) => warning.trekId === selectedTrek.id && activeStatuses.includes(warning.status)), [postedWarnings, selectedTrek]);
  const assessment = useMemo(() => assessRoute(routeWarnings), [routeWarnings]);

  useEffect(() => { let cancelled = false; void Promise.all([getStoredWarnings(), getRoutePackage("annapurna-base-camp")]).then(async ([stored, routePackage]) => { let combined = mergeWarnings(stored); if (navigator.onLine) { try { const remote = await warningApi.list(); await Promise.all(remote.map(saveWarning)); combined = mergeStoredAndRemote(stored, remote); } catch { /* Local data remains available when the service cannot be reached. */ } } if (!cancelled) { setPostedWarnings(combined); setOfflinePackage(routePackage); } }).catch(() => setToast("Saved trail data could not be read in this browser.")).finally(() => { if (!cancelled) setStorageLoading(false); }); return () => { cancelled = true; }; }, []);
  useEffect(() => { const update = () => setOnline(navigator.onLine); update(); window.addEventListener("online", update); window.addEventListener("offline", update); return () => { window.removeEventListener("online", update); window.removeEventListener("offline", update); }; }, []);
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(""), 5200); return () => window.clearTimeout(timer); }, [toast]);

  async function handleSearch(event?: FormEvent) { event?.preventDefault(); setLoading(true); try { setResults(await mockTrekService.search(query)); setScreen("explore"); } catch { setToast("Routes could not be loaded. Try again."); } finally { setLoading(false); } }
  function openTrek(trek: Trek) { setSelectedTrek(trek); setSelectedWarning(null); setScreen("details"); window.scrollTo({ top: 0, behavior: "smooth" }); }
  function navigate(next: Screen) { setScreen(next); setMenuOpen(false); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function persistAndSet(warning: Warning) { await saveWarning(warning); setPostedWarnings((current) => current.some((item) => item.id === warning.id) ? current.map((item) => item.id === warning.id ? warning : item) : [warning, ...current]); }
  async function submitWarning(warning: Warning) { const pending = { ...warning, syncStatus: "pending" as const }; await persistAndSet(pending); setComposerOpen(false); if (!online) { setToast("Saved on this device. This report has not reached other travellers yet."); return; } try { const stored = await warningApi.upsert(pending); await persistAndSet(stored); setToast("Report submitted for coordinator review."); } catch { setToast("Saved on this device. Upload is waiting for a connection."); } }
  async function syncNow() {
    if (!online || syncing || !pendingCount) return; setSyncing(true);
    const pending = postedWarnings.filter((warning) => warning.syncStatus === "pending").map((warning) => ({ ...warning, clientReportId: warning.clientReportId ?? warning.id }));
    const results = await Promise.allSettled(pending.map(warningApi.upsert));
    const synced = results.flatMap((result) => result.status === "fulfilled" ? [result.value] : []);
    await Promise.all(synced.map(saveWarning)); const byId = new Map(synced.map((warning) => [warning.id, warning]));
    setPostedWarnings((current) => current.map((warning) => byId.get(warning.id) ?? warning)); setSyncing(false); setToast(synced.length === pending.length ? `${synced.length} report${synced.length === 1 ? "" : "s"} synced.` : `${synced.length} of ${pending.length} reports synced. Unsent reports remain on this device.`);
  }
  async function updateWarning(id: string, changes: Partial<Warning>, message: string) { const current = postedWarnings.find((warning) => warning.id === id); if (!current) return; const updated = { ...current, ...changes, clientReportId: current.clientReportId ?? current.id, syncStatus: "pending" as const }; await persistAndSet(updated); setSelectedWarning((selected) => selected?.id === id ? updated : selected); if (!online) { setToast("Saved on this device and waiting to upload."); return; } try { const stored = await warningApi.update(updated); await persistAndSet(stored); setSelectedWarning((selected) => selected?.id === id ? stored : selected); setToast(message); } catch { setToast("Saved on this device. Upload is waiting for a connection."); } }
  async function confirmWarning(warning: Warning, kind: ConfirmationKind) {
    const confirmation = { id: `confirmation-${Date.now()}`, kind, createdAt: new Date().toISOString(), source: "Traveller confirmation" };
    const positive = kind === "still_present" || kind === "condition_worsened"; const status = positive && warning.status === "unconfirmed" ? "community_confirmed" : warning.status;
    await updateWarning(warning.id, { confirmations: [...warning.confirmations, confirmation], reportCount: positive ? warning.reportCount + 1 : warning.reportCount, lastConfirmedAt: confirmation.createdAt, status, syncStatus: warning.dataStatus === "community" ? "pending" : warning.syncStatus }, "Confirmation saved on this device. Conditions may have changed.");
  }
  async function downloadTrail() {
    if (selectedTrek.id !== "annapurna-base-camp") { setToast("Offline packages are currently available for the ABC demo route only."); return; }
    const routePackage: OfflineRoutePackage = { trekId: selectedTrek.id, savedAt: new Date().toISOString(), warningCount: routeWarnings.length, trek: selectedTrek, warnings: routeWarnings, places: mapPlaces, route: abcRouteJson, emergencyContacts: contacts, checkpoints };
    await saveRoutePackage(routePackage); cacheOfflineAssets(); setOfflinePackage(routePackage); setToast("ABC trail information is available offline. Online map tiles may still be limited.");
  }
  function inspectWarning(warning: Warning) { setSelectedTrek(treks.find((item) => item.id === warning.trekId) ?? treks[0]); setSelectedWarning(warning); setScreen("details"); window.scrollTo({ top: 0, behavior: "smooth" }); }

  return <div className="app-shell">
    <header className="topbar"><button type="button" className="mobile-menu" onClick={() => setMenuOpen(true)} aria-label="Open navigation"><Menu /></button><AppLogo /><nav className="desktop-nav" aria-label="Primary navigation">{navItems.map((item) => <button type="button" key={item.id} className={screen === item.id ? "active" : ""} onClick={() => navigate(item.id)}>{item.label}</button>)}</nav><div className="topbar-actions"><button type="button" className="top-report-button" onClick={() => setComposerOpen(true)}><AlertTriangle size={17} />Report hazard</button></div></header>
    <div className={`mobile-drawer ${menuOpen ? "mobile-drawer--open" : ""}`} aria-hidden={!menuOpen}><div className="drawer-scrim" onClick={() => setMenuOpen(false)} /><aside><div className="drawer-head"><AppLogo /><button className="icon-button" onClick={() => setMenuOpen(false)} aria-label="Close navigation"><X /></button></div>{navItems.map((item) => <button type="button" key={item.id} onClick={() => navigate(item.id)}><item.icon size={19} />{item.label}</button>)}</aside></div>
    <main aria-busy={storageLoading}>{storageLoading ? <div className="page loading-state"><span className="spinner" />Loading saved trail data…</div> : <>
      {screen === "home" && <HomeScreen query={query} setQuery={setQuery} handleSearch={handleSearch} loading={loading} onOpen={openTrek} onExplore={() => navigate("explore")} onCommunity={() => navigate("community")} activeCount={postedWarnings.filter((warning) => warning.trekId === "annapurna-base-camp" && activeStatuses.includes(warning.status)).length} />}
      {screen === "explore" && <ExploreScreen query={query} setQuery={setQuery} handleSearch={handleSearch} results={results} loading={loading} onOpen={openTrek} />}
      {screen === "nearby" && <NearbyScreen filter={nearbyFilter} setFilter={setNearbyFilter} />}
      {screen === "community" && <CommunityScreen warnings={postedWarnings} expanded={expandedWarnings} setExpanded={setExpandedWarnings} pendingCount={pendingCount} syncing={syncing} onSync={() => void syncNow()} onCreate={() => setComposerOpen(true)} onFlag={(warning) => void updateWarning(warning.id, { status: "disputed" }, "Flag recorded for coordinator review.")} onConfirm={(warning, kind) => void confirmWarning(warning, kind)} />}
      {screen === "coordinator" && <CoordinatorDashboard warnings={postedWarnings} onStatusChange={(id, status) => void updateWarning(id, { status, verified: status === "guide_verified" }, `${status.replaceAll("_", " ")} saved. The trail map now uses this status.`)} onPublicUpdate={(id, update) => void updateWarning(id, { publicUpdate: update }, "Coordinator update published with the warning.")} onInspect={inspectWarning} />}
      {screen === "details" && <DetailsScreen trek={selectedTrek} warnings={routeWarnings} assessment={assessment} offlinePackage={selectedTrek.id === "annapurna-base-camp" ? offlinePackage : undefined} selectedWarning={selectedWarning} setSelectedWarning={setSelectedWarning} onBack={() => navigate("home")} onReport={() => setComposerOpen(true)} onAssistance={() => setAssistanceOpen(true)} onDownload={() => void downloadTrail()} onConfirm={(warning, kind) => void confirmWarning(warning, kind)} />}
    </>}</main>
    <nav className="bottom-nav" aria-label="Mobile navigation">{navItems.map((item) => <button type="button" key={item.id} className={screen === item.id ? "active" : ""} onClick={() => navigate(item.id)}><item.icon size={20} /><span>{item.label}</span></button>)}</nav>
    {!composerOpen && screen !== "coordinator" && screen !== "details" && <button type="button" className="mobile-report-fab" onClick={() => setComposerOpen(true)}><AlertTriangle size={20} />Report hazard</button>}
    {composerOpen && <WarningComposer trek={selectedTrek} online={online} onClose={() => setComposerOpen(false)} onSubmit={(warning) => void submitWarning(warning)} />}
    {assistanceOpen && <AssistancePanel online={online} routePackage={offlinePackage} onClose={() => setAssistanceOpen(false)} />}
    {toast && <div className="toast" role="status">{toast}</div>}
  </div>;
}

function HomeScreen({ query, setQuery, handleSearch, loading, onOpen, onExplore, onCommunity, activeCount }: { query: string; setQuery: (value: string) => void; handleSearch: (event?: FormEvent) => void; loading: boolean; onOpen: (trek: Trek) => void; onExplore: () => void; onCommunity: () => void; activeCount: number }) {
  return <div className="page home-page"><section className="home-intro"><div><p className="eyebrow eyebrow--accent">TREK PLANNER</p><h1>Plan with trail conditions in view.</h1><p className="intro-copy">Recorded routes, field reports and practical stops for trekking in Nepal.</p></div><div className="field-summary"><strong>ABC corridor</strong><span>{activeCount} active warning{activeCount === 1 ? "" : "s"}</span><small>Conditions may have changed</small></div></section><form className="route-search" onSubmit={handleSearch}><Search size={21} /><label className="sr-only" htmlFor="home-search">Search for a trek or region</label><input id="home-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search trek or region" /><button type="submit" className="primary-button">{loading ? "Searching…" : "Find route"}<Navigation size={17} /></button></form><section className="section-block"><div className="section-heading"><div><p className="eyebrow">RECOMMENDED</p><h2>Popular routes</h2></div><button className="text-button" onClick={onExplore}>See all <ChevronRight size={17} /></button></div><div className="recommended-grid">{treks.slice(0, 3).map((trek, index) => <TrailCard key={trek.id} trek={trek} featured={index === 0} onOpen={onOpen} />)}</div></section><section className="safety-strip"><div className="safety-icon"><ShieldCheck /></div><div><p className="eyebrow">COMMUNITY SAFETY</p><h2>{activeCount} reports affect the ABC corridor</h2><p>Review evidence and verification status before making a route decision.</p></div><button type="button" className="secondary-button" onClick={onCommunity}>Review reports</button></section></div>;
}

function ExploreScreen({ query, setQuery, handleSearch, results, loading, onOpen }: { query: string; setQuery: (value: string) => void; handleSearch: (event?: FormEvent) => void; results: Trek[]; loading: boolean; onOpen: (trek: Trek) => void }) { const [difficulty, setDifficulty] = useState("All"); const filtered = difficulty === "All" ? results : results.filter((trek) => trek.difficulty === difficulty); return <div className="page"><div className="page-title"><p className="eyebrow eyebrow--accent">ROUTE LIBRARY</p><h1>Explore treks</h1><p>Compare distance, altitude, difficulty and reported conditions.</p></div><form className="route-search route-search--compact" onSubmit={handleSearch}><Search size={21} /><input aria-label="Search treks" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search trek, region or tag" /><button className="primary-button">Search</button></form><div className="filter-row">{["All", "Easy", "Moderate", "Challenging"].map((item) => <button type="button" className={difficulty === item ? "active" : ""} onClick={() => setDifficulty(item)} key={item}>{item}</button>)}</div>{loading ? <div className="loading-grid">{[1,2,3].map((item) => <div className="skeleton-card" key={item} />)}</div> : filtered.length ? <div className="explore-grid">{filtered.map((trek) => <TrailCard key={trek.id} trek={trek} onOpen={onOpen} />)}</div> : <div className="empty-state"><Compass /><h2>No trails found</h2><p>Try another region or remove the filter.</p></div>}</div>; }

const nearbyKinds = [{ label: "All", icon: MapPin }, { label: "Lodge", icon: Hotel }, { label: "Local business", icon: Building2 }, { label: "EV charger", icon: PlugZap }, { label: "Fuel pump", icon: Fuel }, { label: "Trekking group", icon: Users }];
function NearbyScreen({ filter, setFilter }: { filter: string; setFilter: (value: string) => void }) { const visible = filter === "All" ? nearbyPlaces : nearbyPlaces.filter((place) => place.kind === filter); return <div className="page nearby-page"><div className="page-title"><p className="eyebrow eyebrow--accent">NEARBY</p><h1>Useful stops</h1><p>Demo listings plus named OpenStreetMap places on the ABC route.</p></div><div className="nearby-layout"><div><div className="filter-row filter-row--scroll">{nearbyKinds.map((item) => <button type="button" key={item.label} className={filter === item.label ? "active" : ""} onClick={() => setFilter(item.label)}><item.icon size={16} />{item.label}</button>)}</div><div className="nearby-list">{visible.map((place) => <NearbyCard key={place.id} place={place} />)}</div></div><RouteMap warnings={[]} onWarningSelect={() => undefined} compact trekId="annapurna-base-camp" /></div></div>; }
function NearbyCard({ place }: { place: NearbyPlace }) { const Icon = place.kind === "Lodge" ? Hotel : place.kind === "EV charger" ? PlugZap : place.kind === "Fuel pump" ? Fuel : place.kind === "Trekking group" ? Users : Building2; return <article className="nearby-card"><span className="nearby-card__icon"><Icon /></span><div><div className="nearby-card__title"><h3>{place.name}</h3><span className={place.open ? "open" : "closed"}>{place.open ? "Open" : "Closed"}</span></div><p>{place.kind} · {place.meta}</p><span><Navigation size={14} />{place.distanceKm} km away</span></div></article>; }

function CommunityScreen({ warnings, expanded, setExpanded, pendingCount, syncing, onSync, onCreate, onFlag, onConfirm }: { warnings: Warning[]; expanded: boolean; setExpanded: (value: boolean) => void; pendingCount: number; syncing: boolean; onSync: () => void; onCreate: () => void; onFlag: (warning: Warning) => void; onConfirm: (warning: Warning, kind: ConfirmationKind) => void }) { const visible = expanded ? warnings : warnings.slice(0, 2); return <div className="page community-page"><div className="community-hero"><div><p className="eyebrow eyebrow--light">FIELD REPORTS</p><h1>What travellers saw on the trail.</h1><p>Evidence and verification are shown separately. Conditions may have changed.</p></div><button className="light-button" onClick={onCreate}><Plus size={18} />Report a hazard</button></div><div className="community-layout"><section><div className="section-heading"><div><p className="eyebrow">TRAIL REPORTS</p><h2>Community warnings</h2></div>{pendingCount > 0 ? <button type="button" className="sync-reports-button" onClick={onSync} disabled={syncing}>{syncing ? "Syncing…" : `Sync ${pendingCount}`}</button> : <span className="live-chip">Up to date</span>}</div><div className="warning-list">{visible.map((warning) => <WarningCard key={warning.id} warning={warning} onFlag={onFlag} onConfirm={onConfirm} />)}</div>{warnings.length > 2 && <button type="button" className="secondary-button see-more" onClick={() => setExpanded(!expanded)}>{expanded ? "Show less" : "See more"}<ChevronRight size={17} /></button>}</section><aside className="community-aside"><ShieldCheck /><h3>How confidence works</h3><p>Photos, GPS accuracy, confirmation count and coordinator status remain distinct.</p></aside></div></div>; }

function DetailsScreen({ trek, warnings, assessment, offlinePackage, selectedWarning, setSelectedWarning, onBack, onReport, onAssistance, onDownload, onConfirm }: { trek: Trek; warnings: Warning[]; assessment: ReturnType<typeof assessRoute>; offlinePackage?: OfflineRoutePackage; selectedWarning: Warning | null; setSelectedWarning: (value: Warning | null) => void; onBack: () => void; onReport: () => void; onAssistance: () => void; onDownload: () => void; onConfirm: (warning: Warning, kind: ConfirmationKind) => void }) {
  const [selectedPlace, setSelectedPlace] = useState<MapPlace | null>(null);
  return <div className="details-page"><div className="details-toolbar"><button className="back-button" onClick={onBack}><ChevronLeft size={18} />Back</button><div><p className="eyebrow">ROUTE PLAN</p><h1>{trek.name}</h1></div><SafetyBadge trek={trek} /></div>
    <section className="offline-download"><div><CloudDownload size={21} /><div><strong>{offlinePackage ? "Available offline" : "Download trail offline"}</strong><span>{offlinePackage ? `Last updated ${new Date(offlinePackage.savedAt).toLocaleString()} · ${offlinePackage.warningCount} saved warning${offlinePackage.warningCount === 1 ? "" : "s"}` : "Save the ABC route, places, warnings and emergency information."}</span></div></div><button type="button" onClick={onDownload}>{offlinePackage ? "Update download" : "Download"}</button></section>
    <div className="details-map-wrap"><RouteMap warnings={warnings} onWarningSelect={(warning) => { setSelectedWarning(warning); setSelectedPlace(null); }} onPlaceSelect={(place) => { setSelectedPlace(place); setSelectedWarning(null); }} trekId={trek.id} /><div className="route-overview"><div><span>Total trek</span><strong>{trek.distanceKm} km</strong></div><div><span>Highest point</span><strong>{trek.maxElevationM.toLocaleString()} m</strong></div><div><span>Difficulty</span><strong>{trek.difficulty}</strong></div><div><span>Map places</span><strong>{trek.id === "annapurna-base-camp" ? mapPlaces.length : "Pending"}</strong></div></div></div>
    <div className="details-content"><div className="details-main"><section className="route-safety-summary"><div><AlertTriangle /><div><p className="eyebrow">ROUTE SAFETY SUMMARY</p><h2>{assessment.warningCount} active warning{assessment.warningCount === 1 ? "" : "s"}</h2></div></div><dl><div><dt>Affected section</dt><dd>{assessment.impacted ? assessment.affectedSection : "None reported"}</dd></div><div><dt>Last confirmation</dt><dd>{assessment.lastConfirmedAt ? new Date(assessment.lastConfirmedAt).toLocaleString() : "Not yet independently verified"}</dd></div></dl><p>{assessment.message} Conditions may have changed; no automatic detour is generated.</p></section>
      {selectedWarning && <WarningDetail warning={selectedWarning} onClose={() => setSelectedWarning(null)} onConfirm={onConfirm} />}{selectedPlace && <PlaceDetail place={selectedPlace} onClose={() => setSelectedPlace(null)} />}
      <section className="route-section"><div className="section-heading"><div><p className="eyebrow">AFFECTED AREAS</p><h2>Warnings on this route</h2></div><span>{warnings.length} active</span></div>{warnings.length ? <div className="compact-warnings">{warnings.map((warning) => <button type="button" key={warning.id} onClick={() => { setSelectedWarning(warning); setSelectedPlace(null); }}><span className={`warning-dot warning-dot--${warning.severity}`} /><div><strong>{warning.title}</strong><small>{warning.location} · {warning.reportCount === 1 ? "one report" : `${warning.reportCount} reports`}</small></div><ChevronRight size={17} /></button>)}</div> : <div className="empty-state compact-empty"><CheckCircle2 /><h2>No active reports</h2><p>No saved active warning intersects this route.</p></div>}</section>
    </div><aside className="details-aside"><h2>Route information</h2><div className="condition-card"><span><HeartPulse /></span><div><small>ALTITUDE PROFILE</small><strong>Max {trek.maxElevationM.toLocaleString()} m</strong><p>Allow time for acclimatisation.</p></div></div><div className="condition-card"><span><LocateFixed /></span><div><small>POSITION DATA</small><strong>Recorded trail</strong><p>Route geometry and OSM place data.</p></div></div><h3>Named stays on the map</h3>{mapPlaces.slice(0, 5).map((place) => <button className="mini-place mini-place--button" key={place.id} onClick={() => setSelectedPlace(place)}><BedDouble size={17} /><div><strong>{place.name}</strong><small>{place.note}</small></div></button>)}<p className="source-note">Place data is from OpenStreetMap. Availability is not live.</p></aside></div>
    <div className="floating-actions"><button className="report-button" onClick={onReport}><AlertTriangle size={18} />Report hazard</button><button className="emergency-button" onClick={onAssistance}><PhoneCall size={18} />Request assistance</button></div>
  </div>;
}

function WarningDetail({ warning, onClose, onConfirm }: { warning: Warning; onClose: () => void; onConfirm: (warning: Warning, kind: ConfirmationKind) => void }) { return <section className="selected-warning selected-warning--evidence"><button onClick={onClose} aria-label="Close warning"><X size={17} /></button><div className="detail-status-row"><span className={`warning-type warning-type--${warning.severity}`}>{warning.type} · {warning.severity}</span><span className={`review-status review-status--${warning.status}`}>{warning.status.replaceAll("_", " ")}</span></div><h3>{warning.title}</h3><p>{warning.detail}</p>{warning.photo && <img src={warning.photo} alt={`Field evidence for ${warning.title}`} />}<dl className="warning-facts"><div><dt>Location</dt><dd>{warning.location}</dd></div><div><dt>Source</dt><dd>{warning.source}</dd></div><div><dt>Confirmations</dt><dd>{warning.confirmations.length}</dd></div><div><dt>Report time</dt><dd>{new Date(warning.createdAt).toLocaleString()}</dd></div></dl>{warning.publicUpdate && <p className="public-update">Coordinator update: {warning.publicUpdate}</p>}<details className="confirm-report"><summary>Confirm trail condition</summary><div><button onClick={() => onConfirm(warning, "still_present")}>Still present</button><button onClick={() => onConfirm(warning, "condition_worsened")}>Condition worsened</button><button onClick={() => onConfirm(warning, "trail_passable")}>Trail appears passable</button><button onClick={() => onConfirm(warning, "unable_to_verify")}>Unable to verify</button></div></details></section>; }
function PlaceDetail({ place, onClose }: { place: MapPlace; onClose: () => void }) { return <section className="selected-place"><button onClick={onClose} aria-label="Close place details"><X size={17} /></button><span className="place-category">{place.category}</span><h3>{place.name}</h3><p>{place.note}</p><dl><div><dt>Coordinates</dt><dd>{place.latitude.toFixed(5)}, {place.longitude.toFixed(5)}</dd></div>{place.rooms && <div><dt>OSM rooms tag</dt><dd>{place.rooms}</dd></div>}{place.phone && <div><dt>Mapped phone</dt><dd>{place.phone}</dd></div>}</dl><small>Source: OpenStreetMap contributors · details not independently verified</small></section>; }

function AssistancePanel({ online, routePackage, onClose }: { online: boolean; routePackage?: OfflineRoutePackage; onClose: () => void }) { const availableContacts = routePackage?.emergencyContacts ?? contacts; const availableCheckpoints = routePackage?.checkpoints ?? checkpoints; return <div className="modal" role="dialog" aria-modal="true" aria-labelledby="assistance-title"><div className="modal__scrim" onClick={onClose} /><section className="assistance-panel"><header><div><p className="eyebrow">REQUEST ASSISTANCE</p><h2 id="assistance-title">Call for help directly</h2></div><button className="icon-button" onClick={onClose} aria-label="Close"><X /></button></header><div className={`assistance-state ${online ? "" : "assistance-state--offline"}`}><WifiOff size={19} /><div><strong>{online ? "Use a direct call" : "Saved offline—not transmitted"}</strong><p>{online ? "Call an emergency contact below and share your location and route details." : "This assistance request has not been transmitted. Use a phone call or reach a listed checkpoint."}</p></div></div><h3>Emergency contacts</h3><div className="contact-list">{availableContacts.map((contact) => <a key={contact.number} href={`tel:${contact.number}`}><PhoneCall size={18} /><span><strong>{contact.label}: {contact.number}</strong><small>{contact.note}</small></span></a>)}</div><h3>Downloaded checkpoints</h3><ul>{availableCheckpoints.map((checkpoint) => <li key={checkpoint}>{checkpoint}</li>)}</ul><p className="source-note">Contacts checked against Nepal Tourism Board and Nepal Police listings. Cellular service may be unavailable on the trail.</p></section></div>; }
