"use client";

import { useState } from "react";
import { AlertTriangle, CheckCircle2, Clock3, Eye, MapPin, ShieldCheck } from "lucide-react";
import type { Warning, WarningStatus } from "@/lib/models";

const statusLabels: Record<WarningStatus, string> = { unconfirmed: "Unconfirmed", community_confirmed: "Community Confirmed", guide_verified: "Guide Verified", resolved: "Resolved", outdated: "Outdated", disputed: "Disputed" };

export function CoordinatorDashboard({ warnings, onStatusChange, onPublicUpdate, onInspect }: { warnings: Warning[]; onStatusChange: (id: string, status: WarningStatus) => void; onPublicUpdate: (id: string, update: string) => void; onInspect: (warning: Warning) => void }) {
  const [filter, setFilter] = useState<"all" | WarningStatus>("all");
  const [drafts, setDrafts] = useState<Record<string, string>>({});
  const visible = filter === "all" ? warnings : warnings.filter((warning) => warning.status === filter);
  const pending = warnings.filter((warning) => warning.status === "unconfirmed" || warning.status === "community_confirmed").length;
  return <div className="page coordinator-page">
    <div className="coordinator-heading"><div><p className="eyebrow eyebrow--accent">COORDINATOR DEMO</p><h1>Trail report review</h1><p>Local prototype controls. Authentication and backend moderation are not connected.</p></div><span className="coordinator-role"><ShieldCheck size={17} />Coordinator Demo</span></div>
    <section className="stat-grid" aria-label="Report statistics"><article><Clock3 /><div><span>Needs review</span><strong>{pending}</strong></div></article><article><AlertTriangle /><div><span>Active reports</span><strong>{warnings.filter((warning) => !["resolved", "outdated"].includes(warning.status)).length}</strong></div></article><article><CheckCircle2 /><div><span>Resolved</span><strong>{warnings.filter((warning) => warning.status === "resolved").length}</strong></div></article></section>
    <div className="coordinator-filter"><label>Status <select value={filter} onChange={(event) => setFilter(event.target.value as "all" | WarningStatus)}><option value="all">All reports</option>{(Object.keys(statusLabels) as WarningStatus[]).map((status) => <option key={status} value={status}>{statusLabels[status]}</option>)}</select></label></div>
    {visible.length ? <div className="review-list">{visible.map((warning) => <article className="review-card" key={warning.id}>{warning.photo ? <img src={warning.photo} alt={`Evidence for ${warning.title}`} /> : <div className="review-card__no-photo">No photo</div>}<div className="review-card__body"><div className="review-card__top"><span className={`warning-type warning-type--${warning.severity}`}>{warning.type} · {warning.severity}</span><span className={`review-status review-status--${warning.status}`}>{statusLabels[warning.status]}</span></div><h3>{warning.title}</h3><p>{warning.detail}</p><p className="review-evidence"><MapPin size={14} />{warning.location} · {warning.reportCount} report{warning.reportCount === 1 ? "" : "s"}</p><div className="review-actions"><button type="button" className="inspect-button" onClick={() => onInspect(warning)}><Eye size={16} />Inspect</button><button type="button" className="verify-button" onClick={() => onStatusChange(warning.id, "guide_verified")}><ShieldCheck size={16} />Verify</button><button type="button" onClick={() => onStatusChange(warning.id, "disputed")}>Dispute</button><button type="button" className="resolve-button" onClick={() => onStatusChange(warning.id, "resolved")}><CheckCircle2 size={16} />Resolve</button></div><div className="coordinator-update"><label htmlFor={`update-${warning.id}`}>Public update</label><textarea id={`update-${warning.id}`} rows={2} value={drafts[warning.id] ?? warning.publicUpdate ?? ""} onChange={(event) => setDrafts((current) => ({ ...current, [warning.id]: event.target.value }))} placeholder="Add factual trail information…" /><button type="button" disabled={!(drafts[warning.id] ?? "").trim()} onClick={() => onPublicUpdate(warning.id, (drafts[warning.id] ?? "").trim())}>Publish local update</button></div></div></article>)}</div> : <div className="empty-state"><CheckCircle2 /><h2>No reports in this filter</h2><p>Choose another verification status.</p></div>}
  </div>;
}
